apiVersion: v1
kind: Pod
metadata:
  name: raspbian-sleep
  namespace: default
spec:
  containers:
  - image: luxas/raspbian
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: raspbian-sleep
  restartPolicy: Always