apiVersion: v1
kind: Pod
metadata:
  name: alpine-sleep
  namespace: default
spec:
  containers:
  - image: luxas/alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: alpine-sleep
  restartPolicy: Always