apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  namespace: kube-system
  labels:
    k8s-app: registry
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: registry
  template:
    metadata:
      labels:
        k8s-app: registry
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: luxas/registry
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: registry-data
        hostPath:
          path: /var/lib/registry