apiVersion: v1
kind: Pod
metadata:
  name: alpine-sleep
  namespace: default
spec:
  containers:
  - image: luxas/alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: alpine-sleep
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: raspbian-sleep
  namespace: default
spec:
  containers:
  - image: resin/rpi-raspbian:jessie
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: raspbian-sleep
  restartPolicy: Always
