apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
  labels:
    k8s-app: registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: registry
  clusterIP: 10.0.0.20
  ports:
  - name: registry
    port: 5000
    protocol: TCP
